apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: e2imdiysa-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: e2imdiysa-python 
  name: e2imdiysa-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: e2imdiysa-python 
